### ISSUE TITLE
Crashing in Bitwig 2.2.2 when changing modes

### ISSUE THREAD

**Issue by VeissieV** [dplduffy/MidiFighterTwister-Bitwig-Script#11]
At first wasn't able to change modes until I factory reset the Twister(Got the midifighter utility configuration?), afterword the script crashes when trying to change modes. This seems like a great script. I'd really like to use it and be willing to donate for an update if necessary. 

Thanks

**Comment by JinVeiss** [comment]
I see now from the other issue that we're missing the utility config. Do you still have it?

**Comment by dplduffy** [comment]
Script has been updated many times since this issue.  Functionality isn't the same anymore.
