### ISSUE TITLE
Any love for Bitwig 4?

### ISSUE THREAD

**Issue by VeissieV** [dplduffy/MidiFighterTwister-Bitwig-Script#12]
Please :D

**Comment by dplduffy** [comment]
I'll try to get it updated for 4.  Haven't had a chance to play with it yet.

**Comment by dplduffy** [comment]
Checked it tonight. Good news is the script works, bad news is the documentation is worthless and doesn’t match current functions. I’ll try and get this updated soon.

**Comment by dplduffy** [comment]
Updated the documentation, still a lot to do but I'm closing this and documenting my todo list in the issues area.
